name: CI/CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: exasol/python-toolbox/.github/workflows/check-release-tag.yml@0.3.0

  ci-job:
    name: Checks
    needs: [ check-tag-version-job ]
    uses: exasol/python-toolbox/.github/workflows/checks.yml@main

  tests-job:
    name: Tests (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.2.2

      - name: Install Project
        run: poetry install

      - name: Checkout ITDE
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..

      - name: Start EXASOL Test-Environment
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666 --db-mem-size 4GB
        working-directory: ../integration-test-docker-environment

      - name: Run Tests
        run: poetry run pytest tests

  cd-job:
    name: Continues Delivery
    needs: [ ci-job, tests-job ]
    uses: exasol/python-toolbox/.github/workflows/build-and-publish.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
