name: CI/CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: ./.github/workflows/check-release-tag.yml

  ci-job:
    name: Checks
    needs: [ check-tag-version-job ]
    uses: ./.github/workflows/checks.yml

  tests-job:
    name: Tests (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.14.0
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.2.2

      - name: Run Legacy Tests
        run: poetry run pytest --backend=onprem test_legacy

  cd-job:
    name: Continuous Delivery
    needs: [ ci-job ]
    uses: ./.github/workflows/build-and-publish.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
