name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
  pull_request:
    branches-ignore:
      - 'main'

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml

  publish-docs:
    name: Publish Documentation
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/docs.yml
