name: Publish Documentation

on: workflow_call

jobs:

  documenation-job:
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.2.0

      - name: Poetry Install
        run: poetry install

      - name: Build Documentation
        run: |
          poetry run python -m nox -s build-html-doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ./doc/build-docu
          git-config-name: Github Action
          git-config-email: opensource@exasol.com