name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml

  metrics:
    needs: [ ci-job ]
    uses: ./.github/workflows/report.yml

  tests-job:
    name: Tests (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.2.2

      - name: Install Project
        run: poetry install

      - name: Checkout ITDE
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..

      - name: Start EXASOL Test-Environment
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666 --db-mem-size 4GB
        working-directory: ../integration-test-docker-environment

      - name: Run Tests
        run: poetry run pytest tests

