name: Update Docs

on:
  push:
    branches:
      - 'main'

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/docs.yml
