name: Publish Documentation

on:
  release:
    types: [published]
jobs:

  publish-release-documentation:
    runs-on: ubuntu-latest
    environment: publish
    strategy:
      fail-fast: false

    steps:
    - name: SCM Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.2.0

    - name: Poetry Install
      run: poetry install

    - name: Publish Documentation
      run: |
        git config --local user.email "opensource@exasol.com"
        git config --local user.name "GitHub Action"
        git fetch
        poetry run python -m nox -s push-pages-release
